

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."app_role" AS ENUM (
    'user',
    'staff',
    'admin'
);


ALTER TYPE "public"."app_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."assign_staff_role"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
    staff_record RECORD;
BEGIN
    -- Check if the new user's email is in the staff allowlist
    SELECT * INTO staff_record 
    FROM staff_allowlist 
    WHERE email = NEW.email AND is_active = TRUE;
    
    IF FOUND THEN
        -- Insert a role for the user
        INSERT INTO user_roles (user_id, role)
        VALUES (NEW.id, staff_record.role);
    END IF;
    
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."assign_staff_role"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_user_role"("user_id" "uuid") RETURNS "public"."app_role"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $_$
    SELECT role FROM public.user_roles WHERE user_roles.user_id = $1 LIMIT 1;
$_$;


ALTER FUNCTION "public"."get_user_role"("user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
BEGIN
    -- Only assign user role for public signups (not admin SSO)
    -- Admin users will be manually assigned roles through staff_allowlist
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'user'::public.app_role);
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_staff_allowed"("user_email" "text") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.staff_allowlist 
        WHERE email = user_email AND is_active = true
    );
$$;


ALTER FUNCTION "public"."is_staff_allowed"("user_email" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_created_by"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  if new.created_by is null then
    new.created_by := auth.uid();
  end if;
  return new;
end;
$$;


ALTER FUNCTION "public"."set_created_by"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_products_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_products_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."addresses" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "street" "text",
    "city" "text",
    "houseNumber" "text",
    "postalCode" "text",
    "connections" "text",
    "addition" "text",
    "ownerId" bigint,
    "eanGas" "text",
    "eanElectricity" "text",
    "created_by" "uuid",
    "bloxsReferenceOid" "text",
    "reminderEnabled" boolean DEFAULT false
);


ALTER TABLE "public"."addresses" OWNER TO "postgres";


COMMENT ON COLUMN "public"."addresses"."reminderEnabled" IS 'When enabled, sends reminder notification if no energy tax request has been submitted for over 1 year';



ALTER TABLE "public"."addresses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."address_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company_profile" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "fullName" "text" NOT NULL,
    "ibanName" "text",
    "rsin" "text",
    "phoneNumber" "text",
    "email" "text",
    "street" "text",
    "houseNumber" "text",
    "addition" "text",
    "postalCode" "text",
    "city" "text",
    "country" "text",
    "createdAt" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "userId" "uuid",
    "bloxsEnabled" boolean DEFAULT false
);


ALTER TABLE "public"."company_profile" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."energiebelasting_aanvragen" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "voornaam" "text" NOT NULL,
    "achternaam" "text" NOT NULL,
    "email" "text" NOT NULL,
    "telefoon" "text" NOT NULL,
    "adres" "text" NOT NULL,
    "huisnummer" "text" NOT NULL,
    "postcode" "text" NOT NULL,
    "stad" "text" NOT NULL,
    "opmerkingen" "text",
    "status" "text" DEFAULT 'nieuw'::"text",
    "calculator_jaren" integer,
    "calculator_units" integer,
    "calculator_indicatie" numeric,
    "scan_slaagkans" integer,
    "scan_kans_label" "text",
    CONSTRAINT "energiebelasting_aanvragen_scan_slaagkans_range_chk" CHECK ((("scan_slaagkans" IS NULL) OR (("scan_slaagkans" >= 0) AND ("scan_slaagkans" <= 100))))
);


ALTER TABLE "public"."energiebelasting_aanvragen" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hoog_rendements_glas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "referenceCode" "text",
    "type" "text",
    "maxUValue" "text",
    "subsidyAmount" "text",
    "subsidyAmountHistoricBuilding" "text",
    "subsidyAmountExtra" "text",
    "category" "text",
    "buildingType" "text",
    "brand" "text",
    "glassType" "text",
    "categoryId" "text"
);


ALTER TABLE "public"."hoog_rendements_glas" OWNER TO "postgres";


ALTER TABLE "public"."hoog_rendements_glas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."high_performance_glass_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."insulationRequirements" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "categoryId" "text",
    "minSurface" numeric
);


ALTER TABLE "public"."insulationRequirements" OWNER TO "postgres";


ALTER TABLE "public"."insulationRequirements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."insulationRequirements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isolatie" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "referenceCode" "text",
    "brand" "text",
    "type" "text",
    "materialName" "text",
    "minRdValue" "text",
    "minThicknessMm" "text",
    "subsidyAmount" "text",
    "subsidyAmountExtra" "text",
    "bioBasedBonus" "text",
    "category" "text",
    "buildingType" "text",
    "year" integer DEFAULT 2025,
    "categoryId" "text"
);


ALTER TABLE "public"."isolatie" OWNER TO "postgres";


ALTER TABLE "public"."isolatie" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."insulation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."meldcodes_glas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "meldcode" "text" NOT NULL,
    "hoofdmeldcode" "text",
    "fabrikant" "text" NOT NULL,
    "model" "text" NOT NULL,
    "ug_waarde" numeric,
    "subsidiebedrag_enkel" numeric,
    "subsidiebedrag_meerdere" numeric,
    "subsidiebedrag_monument" numeric,
    "categorie" "text",
    "woning_type" "text",
    "maatregel_type" "text" DEFAULT 'glas'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."meldcodes_glas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meldcodes_isolatie" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "meldcode" "text" NOT NULL,
    "fabrikant" "text" NOT NULL,
    "model" "text" NOT NULL,
    "naam_materiaal" "text",
    "min_waarde_rd" numeric,
    "min_dikte_mm" "text",
    "subsidiebedrag_enkel" numeric,
    "subsidiebedrag_meerdere" numeric,
    "biobased_bonus" numeric,
    "categorie" "text",
    "woning_type" "text",
    "maatregel_type" "text" DEFAULT 'isolatie'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."meldcodes_isolatie" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meldcodes_ventilatie" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "meldcode" "text" NOT NULL,
    "fabrikant" "text" NOT NULL,
    "model" "text" NOT NULL,
    "categorie" "text",
    "subsidiebedrag" numeric,
    "maatregel_type" "text" DEFAULT 'ventilatie'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."meldcodes_ventilatie" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meldcodes_warmtepompen" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "meldcode" "text" NOT NULL,
    "fabrikant" "text" NOT NULL,
    "model" "text" NOT NULL,
    "vermogen_kw" numeric,
    "subsidiebedrag" numeric,
    "subsidiebedrag_2e" numeric,
    "koudemiddel" "text",
    "gwp" integer,
    "categorie" "text",
    "maatregel_type" "text" DEFAULT 'warmtepomp'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."meldcodes_warmtepompen" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meldcodes_zonneboilers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "meldcode" "text" NOT NULL,
    "fabrikant" "text" NOT NULL,
    "model" "text" NOT NULL,
    "jaarproductie_kwh" numeric,
    "subsidiebedrag" numeric,
    "oppervlakte" "text",
    "maatregel_type" "text" DEFAULT 'zonneboiler'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."meldcodes_zonneboilers" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ownerDocuments" (
    "id" bigint NOT NULL,
    "ownerId" bigint NOT NULL,
    "name" "text" NOT NULL,
    "storagePath" "text",
    "mimeType" "text",
    "sizeBytes" bigint,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "documentType" "text" DEFAULT 'authorization'::"text",
    "year" integer
);


ALTER TABLE "public"."ownerDocuments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ownerDocuments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."ownerDocuments_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ownerDocuments_id_seq" OWNED BY "public"."ownerDocuments"."id";



CREATE TABLE IF NOT EXISTS "public"."owners" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "firstName" "text",
    "lastName" "text",
    "emailAddress" "text",
    "phoneNumber" "text",
    "street" "text",
    "houseNumber" "text",
    "postalCode" "text",
    "city" "text",
    "bsnOwner" "text",
    "addition" "text",
    "authorization" "jsonb",
    "displayName" "text" DEFAULT ''::"text",
    "rsinCompany" "text",
    "ownerType" "jsonb",
    "created_by" "uuid",
    "bloxsReferenceOid" "text",
    "pricingTypeSvohIsde" "text",
    "pricingValueSvohIsde" numeric(10,2),
    "pricingTypeEnergie" "text",
    "pricingValueEnergie" numeric,
    "prefix" "text",
    "gender" "text",
    "country" "text",
    "iban" "text",
    "hasDifferentCorrespondenceAddress" boolean DEFAULT false,
    "correspondenceStreet" "text",
    "correspondenceHouseNumber" "text",
    "correspondenceAddition" "text",
    "correspondencePostalCode" "text",
    "correspondenceCity" "text",
    "correspondenceCountry" "text",
    "kvkNumber" "text",
    "hasDifferentInvoiceDetails" boolean DEFAULT false,
    "invoiceName" "text",
    "invoiceIdentifier" "text",
    "companyName" "text",
    "noVat" boolean,
    CONSTRAINT "owners_pricingTypeSvohIsde_check" CHECK (("pricingTypeSvohIsde" = ANY (ARRAY['percentage'::"text", 'fixed'::"text", NULL::"text"])))
);


ALTER TABLE "public"."owners" OWNER TO "postgres";


COMMENT ON COLUMN "public"."owners"."bloxsReferenceOid" IS 'Reference ID van het Bloxs contact (OID)';



COMMENT ON COLUMN "public"."owners"."hasDifferentInvoiceDetails" IS 'Use alternative name/identifier on invoices';



COMMENT ON COLUMN "public"."owners"."invoiceName" IS 'Alternative name to display on invoices';



COMMENT ON COLUMN "public"."owners"."invoiceIdentifier" IS 'Alternative BSN (person) or RSIN (company) for invoices';



ALTER TABLE "public"."owners" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."owners_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."requestDocuments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "requestId" bigint NOT NULL,
    "name" "text" NOT NULL,
    "storagePath" "text",
    "mimeType" "text",
    "sizeBytes" bigint,
    "created_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" "text" DEFAULT 'overig'::"text"
);


ALTER TABLE "public"."requestDocuments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."requests" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "startDate" "text",
    "endDate" "text",
    "status" "text" DEFAULT ''::"text",
    "addressId" bigint,
    "reference" "text" DEFAULT ''::"text",
    "requestAmount" "text" DEFAULT ''::"text",
    "invoiceNumber" "text" DEFAULT ''::"text",
    "note" "text" DEFAULT ''::"text",
    "invoiceAmount" "text" DEFAULT ''::"text",
    "usageElectricity" "text" DEFAULT ''::"text",
    "usageGas" "text" DEFAULT ''::"text",
    "taxElectricity" "text" DEFAULT ''::"text",
    "taxGas" "text" DEFAULT ''::"text",
    "taxDiscount" "text" DEFAULT ''::"text",
    "taxGasOde" "text" DEFAULT ''::"text",
    "taxElectricityOde" "text" DEFAULT ''::"text",
    "inclusiveVat" "text" DEFAULT ''::"text",
    "created_by" "uuid",
    "requestType" numeric,
    "bloxs_invoice_reference" "text",
    "serviceNumber" "text",
    "executionDate" "text",
    "measure" "text",
    "reportCode" "text",
    "executionCompany" "text",
    "executionCompanyKvk" "text"
);


ALTER TABLE "public"."requests" OWNER TO "postgres";


ALTER TABLE "public"."requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."staff_allowlist" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "role" "public"."app_role" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" "uuid",
    "is_active" boolean DEFAULT true NOT NULL,
    CONSTRAINT "staff_allowlist_role_check" CHECK (("role" = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])))
);


ALTER TABLE "public"."staff_allowlist" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subsidie_aanvragen" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "voornaam" "text" NOT NULL,
    "achternaam" "text" NOT NULL,
    "email" "text" NOT NULL,
    "telefoon" "text" NOT NULL,
    "maatregel" "text" NOT NULL,
    "isolatie_type" "text",
    "al_geinstalleerd" boolean NOT NULL,
    "installatiejaar" "text",
    "opmerkingen" "text",
    "factuur_urls" "text"[],
    "doelgroep" "text" NOT NULL,
    "regeling" "text" NOT NULL,
    "status" "text" DEFAULT 'nieuw'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."subsidie_aanvragen" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."svoh_aanvragen" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "voornaam" "text" NOT NULL,
    "achternaam" "text" NOT NULL,
    "email" "text" NOT NULL,
    "telefoon" "text" NOT NULL,
    "maatregelen" "jsonb" NOT NULL,
    "document_urls" "text"[],
    "regeling" "text" DEFAULT 'SVOH'::"text" NOT NULL,
    "status" "text" DEFAULT 'nieuw'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."svoh_aanvragen" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role" "public"."app_role" DEFAULT 'user'::"public"."app_role" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_roles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."warmtepompen" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nameRefrigerant" "text" NOT NULL,
    "type" "text" NOT NULL,
    "brand" "text" NOT NULL,
    "referenceCode" "text",
    "subsidyAmount" "text",
    "year" integer DEFAULT EXTRACT(year FROM "now"()) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "globalWarmingPotential" "text",
    "category" "text",
    "capacity" "text"
);


ALTER TABLE "public"."warmtepompen" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."zonneboilers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "referenceCode" "text",
    "brand" "text",
    "type" "text",
    "capacity" "text",
    "subsidyAmount" "text",
    "surface" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."zonneboilers" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ownerDocuments" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ownerDocuments_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."addresses"
    ADD CONSTRAINT "address_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company_profile"
    ADD CONSTRAINT "company_profile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."energiebelasting_aanvragen"
    ADD CONSTRAINT "energiebelasting_aanvragen_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hoog_rendements_glas"
    ADD CONSTRAINT "high_performance_glass_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."insulationRequirements"
    ADD CONSTRAINT "insulationRequirements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."isolatie"
    ADD CONSTRAINT "insulation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meldcodes_glas"
    ADD CONSTRAINT "meldcodes_glas_meldcode_key" UNIQUE ("meldcode");



ALTER TABLE ONLY "public"."meldcodes_glas"
    ADD CONSTRAINT "meldcodes_glas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meldcodes_isolatie"
    ADD CONSTRAINT "meldcodes_isolatie_meldcode_key" UNIQUE ("meldcode");



ALTER TABLE ONLY "public"."meldcodes_isolatie"
    ADD CONSTRAINT "meldcodes_isolatie_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meldcodes_ventilatie"
    ADD CONSTRAINT "meldcodes_ventilatie_meldcode_key" UNIQUE ("meldcode");



ALTER TABLE ONLY "public"."meldcodes_ventilatie"
    ADD CONSTRAINT "meldcodes_ventilatie_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meldcodes_warmtepompen"
    ADD CONSTRAINT "meldcodes_warmtepompen_meldcode_key" UNIQUE ("meldcode");



ALTER TABLE ONLY "public"."meldcodes_warmtepompen"
    ADD CONSTRAINT "meldcodes_warmtepompen_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meldcodes_zonneboilers"
    ADD CONSTRAINT "meldcodes_zonneboilers_meldcode_key" UNIQUE ("meldcode");



ALTER TABLE ONLY "public"."meldcodes_zonneboilers"
    ADD CONSTRAINT "meldcodes_zonneboilers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ownerDocuments"
    ADD CONSTRAINT "ownerDocuments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."owners"
    ADD CONSTRAINT "owners_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."warmtepompen"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."requestDocuments"
    ADD CONSTRAINT "request_documents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."requests"
    ADD CONSTRAINT "requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."zonneboilers"
    ADD CONSTRAINT "solarwaterheaters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."staff_allowlist"
    ADD CONSTRAINT "staff_allowlist_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."staff_allowlist"
    ADD CONSTRAINT "staff_allowlist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subsidie_aanvragen"
    ADD CONSTRAINT "subsidie_aanvragen_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."svoh_aanvragen"
    ADD CONSTRAINT "svoh_aanvragen_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_role_key" UNIQUE ("user_id", "role");



CREATE INDEX "addresses_created_by_idx" ON "public"."addresses" USING "btree" ("created_by");



CREATE INDEX "idx_addresses_bloxs_reference" ON "public"."addresses" USING "btree" ("bloxsReferenceOid");



CREATE INDEX "idx_addresses_reminder_enabled" ON "public"."addresses" USING "btree" ("reminderEnabled") WHERE ("reminderEnabled" = true);



CREATE INDEX "idx_glas_categorie" ON "public"."meldcodes_glas" USING "btree" ("categorie");



CREATE INDEX "idx_glas_fabrikant" ON "public"."meldcodes_glas" USING "btree" ("fabrikant");



CREATE INDEX "idx_glas_hoofdmeldcode" ON "public"."meldcodes_glas" USING "btree" ("hoofdmeldcode");



CREATE INDEX "idx_glas_meldcode" ON "public"."meldcodes_glas" USING "btree" ("meldcode");



CREATE INDEX "idx_glas_search" ON "public"."meldcodes_glas" USING "gin" ("to_tsvector"('"dutch"'::"regconfig", (((("fabrikant" || ' '::"text") || "model") || ' '::"text") || "meldcode")));



CREATE INDEX "idx_isolatie_categorie" ON "public"."meldcodes_isolatie" USING "btree" ("categorie");



CREATE INDEX "idx_isolatie_fabrikant" ON "public"."meldcodes_isolatie" USING "btree" ("fabrikant");



CREATE INDEX "idx_isolatie_meldcode" ON "public"."meldcodes_isolatie" USING "btree" ("meldcode");



CREATE INDEX "idx_isolatie_search" ON "public"."meldcodes_isolatie" USING "gin" ("to_tsvector"('"dutch"'::"regconfig", (((("fabrikant" || ' '::"text") || "model") || ' '::"text") || "meldcode")));



CREATE INDEX "idx_meldcodes_fabrikant" ON "public"."meldcodes_warmtepompen" USING "btree" ("fabrikant");



CREATE INDEX "idx_meldcodes_meldcode" ON "public"."meldcodes_warmtepompen" USING "btree" ("meldcode");



CREATE INDEX "idx_meldcodes_model" ON "public"."meldcodes_warmtepompen" USING "btree" ("model");



CREATE INDEX "idx_meldcodes_search" ON "public"."meldcodes_warmtepompen" USING "gin" ("to_tsvector"('"dutch"'::"regconfig", (((("fabrikant" || ' '::"text") || "model") || ' '::"text") || "meldcode")));



CREATE INDEX "idx_ownerDocuments_created_at" ON "public"."ownerDocuments" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_ownerDocuments_ownerId" ON "public"."ownerDocuments" USING "btree" ("ownerId");



CREATE INDEX "idx_owners_bloxs_reference" ON "public"."owners" USING "btree" ("bloxsReferenceOid");



CREATE INDEX "idx_products_active" ON "public"."warmtepompen" USING "btree" ("is_active");



CREATE INDEX "idx_products_brand" ON "public"."warmtepompen" USING "btree" ("brand");



CREATE INDEX "idx_products_type" ON "public"."warmtepompen" USING "btree" ("type");



CREATE INDEX "idx_products_year" ON "public"."warmtepompen" USING "btree" ("year");



CREATE INDEX "idx_requests_bloxs_invoice_reference" ON "public"."requests" USING "btree" ("bloxs_invoice_reference");



CREATE INDEX "idx_ventilatie_categorie" ON "public"."meldcodes_ventilatie" USING "btree" ("categorie");



CREATE INDEX "idx_ventilatie_fabrikant" ON "public"."meldcodes_ventilatie" USING "btree" ("fabrikant");



CREATE INDEX "idx_ventilatie_meldcode" ON "public"."meldcodes_ventilatie" USING "btree" ("meldcode");



CREATE INDEX "idx_ventilatie_search" ON "public"."meldcodes_ventilatie" USING "gin" ("to_tsvector"('"dutch"'::"regconfig", (((("fabrikant" || ' '::"text") || "model") || ' '::"text") || "meldcode")));



CREATE INDEX "idx_zonneboilers_fabrikant" ON "public"."meldcodes_zonneboilers" USING "btree" ("fabrikant");



CREATE INDEX "idx_zonneboilers_meldcode" ON "public"."meldcodes_zonneboilers" USING "btree" ("meldcode");



CREATE INDEX "idx_zonneboilers_search" ON "public"."meldcodes_zonneboilers" USING "gin" ("to_tsvector"('"dutch"'::"regconfig", (((("fabrikant" || ' '::"text") || "model") || ' '::"text") || "meldcode")));



CREATE INDEX "insulation_category_norm_idx" ON "public"."isolatie" USING "btree" ("regexp_replace"("regexp_replace"("lower"("btrim"("replace"("category", ' '::"text", ' '::"text"))), '[\s]+'::"text", ''::"text", 'g'::"text"), '[-–]'::"text", ''::"text", 'g'::"text"));



CREATE INDEX "owners_created_by_idx" ON "public"."owners" USING "btree" ("created_by");



CREATE INDEX "requests_created_by_idx" ON "public"."requests" USING "btree" ("created_by");



CREATE OR REPLACE TRIGGER "set_created_by_addresses" BEFORE INSERT ON "public"."addresses" FOR EACH ROW EXECUTE FUNCTION "public"."set_created_by"();



CREATE OR REPLACE TRIGGER "set_created_by_owners" BEFORE INSERT ON "public"."owners" FOR EACH ROW EXECUTE FUNCTION "public"."set_created_by"();



CREATE OR REPLACE TRIGGER "set_created_by_requests" BEFORE INSERT ON "public"."requests" FOR EACH ROW EXECUTE FUNCTION "public"."set_created_by"();



CREATE OR REPLACE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."subsidie_aanvragen" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "update_ownerdocuments_updated_at" BEFORE UPDATE ON "public"."ownerDocuments" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_products_updated_at" BEFORE UPDATE ON "public"."warmtepompen" FOR EACH ROW EXECUTE FUNCTION "public"."update_products_updated_at"();



CREATE OR REPLACE TRIGGER "update_solarwaterheaters_updated_at" BEFORE UPDATE ON "public"."zonneboilers" FOR EACH ROW EXECUTE FUNCTION "public"."update_products_updated_at"();



ALTER TABLE ONLY "public"."addresses"
    ADD CONSTRAINT "addresses_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "public"."owners"("id");



ALTER TABLE ONLY "public"."company_profile"
    ADD CONSTRAINT "company_profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ownerDocuments"
    ADD CONSTRAINT "ownerDocuments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."ownerDocuments"
    ADD CONSTRAINT "ownerDocuments_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "public"."owners"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."requestDocuments"
    ADD CONSTRAINT "requestDocuments_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "public"."requests"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."requestDocuments"
    ADD CONSTRAINT "request_documents_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."requests"
    ADD CONSTRAINT "requests_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "public"."addresses"("id");



ALTER TABLE ONLY "public"."staff_allowlist"
    ADD CONSTRAINT "staff_allowlist_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."user_roles"
    ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Aanvragen indienen" ON "public"."subsidie_aanvragen" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Addresses: staff/admin full access" ON "public"."addresses" USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"]))) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "Addresses: users can delete own" ON "public"."addresses" FOR DELETE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Addresses: users can insert own" ON "public"."addresses" FOR INSERT WITH CHECK (("created_by" = "auth"."uid"()));



CREATE POLICY "Addresses: users can update own" ON "public"."addresses" FOR UPDATE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Addresses: users can view own" ON "public"."addresses" FOR SELECT USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Admin can delete addresses" ON "public"."addresses" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can delete owners" ON "public"."owners" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can delete requests" ON "public"."requests" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can insert addresses" ON "public"."addresses" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can insert owners" ON "public"."owners" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can insert requests" ON "public"."requests" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can update addresses" ON "public"."addresses" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text")) WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can update owners" ON "public"."owners" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text")) WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can update requests" ON "public"."requests" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text")) WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can view all addresses" ON "public"."addresses" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can view all owners" ON "public"."owners" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admin can view all requests" ON "public"."requests" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "Admins can manage allowlist" ON "public"."staff_allowlist" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"public"."app_role"));



CREATE POLICY "Admins can manage roles" ON "public"."user_roles" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"public"."app_role"));



CREATE POLICY "Allow authenticated users to insert owner documents" ON "public"."ownerDocuments" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow authenticated users to read owner documents" ON "public"."ownerDocuments" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow read access for all users" ON "public"."insulationRequirements" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow users to delete owner documents" ON "public"."ownerDocuments" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Allow users to update owner documents" ON "public"."ownerDocuments" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete glass products" ON "public"."hoog_rendements_glas" FOR DELETE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can delete insulation products" ON "public"."isolatie" FOR DELETE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can delete products" ON "public"."warmtepompen" FOR DELETE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can delete solar water heaters" ON "public"."zonneboilers" FOR DELETE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can insert glass products" ON "public"."hoog_rendements_glas" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can insert insulation products" ON "public"."isolatie" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can insert products" ON "public"."warmtepompen" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can insert solar water heaters" ON "public"."zonneboilers" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can update glass products" ON "public"."hoog_rendements_glas" FOR UPDATE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can update insulation products" ON "public"."isolatie" FOR UPDATE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can update products" ON "public"."warmtepompen" FOR UPDATE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can update solar water heaters" ON "public"."zonneboilers" FOR UPDATE USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "High performance glass products are viewable by everyone" ON "public"."hoog_rendements_glas" FOR SELECT USING (true);



CREATE POLICY "Insulation products are viewable by everyone" ON "public"."isolatie" FOR SELECT USING (true);



CREATE POLICY "Owners: staff/admin full access" ON "public"."owners" USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"]))) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "Owners: users can delete own" ON "public"."owners" FOR DELETE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Owners: users can insert own" ON "public"."owners" FOR INSERT WITH CHECK (("created_by" = "auth"."uid"()));



CREATE POLICY "Owners: users can update own" ON "public"."owners" FOR UPDATE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Owners: users can view own" ON "public"."owners" FOR SELECT USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Products are viewable by everyone" ON "public"."warmtepompen" FOR SELECT USING (true);



CREATE POLICY "Publiek leesbaar" ON "public"."meldcodes_glas" FOR SELECT USING (true);



CREATE POLICY "Publiek leesbaar" ON "public"."meldcodes_isolatie" FOR SELECT USING (true);



CREATE POLICY "Publiek leesbaar" ON "public"."meldcodes_ventilatie" FOR SELECT USING (true);



CREATE POLICY "Publiek leesbaar" ON "public"."meldcodes_warmtepompen" FOR SELECT USING (true);



CREATE POLICY "Publiek leesbaar" ON "public"."meldcodes_zonneboilers" FOR SELECT USING (true);



CREATE POLICY "RequestDocuments: Admin can manage all" ON "public"."requestDocuments" TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text")) WITH CHECK ((( SELECT "auth"."email"() AS "email") = 'koshemerik@gmail.com'::"text"));



CREATE POLICY "RequestDocuments: staff/admin full access" ON "public"."requestDocuments" USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"]))) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "RequestDocuments: users can delete own" ON "public"."requestDocuments" FOR DELETE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "RequestDocuments: users can insert own" ON "public"."requestDocuments" FOR INSERT WITH CHECK (("created_by" = "auth"."uid"()));



CREATE POLICY "RequestDocuments: users can update own" ON "public"."requestDocuments" FOR UPDATE USING (("created_by" = "auth"."uid"())) WITH CHECK (("created_by" = "auth"."uid"()));



CREATE POLICY "RequestDocuments: users can view own" ON "public"."requestDocuments" FOR SELECT USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Requests: staff/admin full access" ON "public"."requests" USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"]))) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "Requests: users can delete own" ON "public"."requests" FOR DELETE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Requests: users can insert own" ON "public"."requests" FOR INSERT WITH CHECK (("created_by" = "auth"."uid"()));



CREATE POLICY "Requests: users can update own" ON "public"."requests" FOR UPDATE USING (("created_by" = "auth"."uid"()));



CREATE POLICY "Requests: users can view own" ON "public"."requests" FOR SELECT USING (("created_by" = "auth"."uid"()));



CREATE POLICY "SVOH aanvragen indienen" ON "public"."svoh_aanvragen" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Solar water heaters are viewable by everyone" ON "public"."zonneboilers" FOR SELECT USING (true);



CREATE POLICY "Staff can view all roles" ON "public"."user_roles" FOR SELECT USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "Staff can view allowlist" ON "public"."staff_allowlist" FOR SELECT USING (("public"."get_user_role"("auth"."uid"()) = ANY (ARRAY['staff'::"public"."app_role", 'admin'::"public"."app_role"])));



CREATE POLICY "Users can manage their own company profile" ON "public"."company_profile" USING (("auth"."uid"() = "userId")) WITH CHECK (("auth"."uid"() = "userId"));



CREATE POLICY "Users can view own roles" ON "public"."user_roles" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."addresses" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "anon_insert_energiebelasting_aanvragen" ON "public"."energiebelasting_aanvragen" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "anon_insert_subsidie_aanvragen" ON "public"."subsidie_aanvragen" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "anon_read_meldcodes_ventilatie" ON "public"."meldcodes_ventilatie" FOR SELECT TO "anon" USING (true);



CREATE POLICY "anon_read_meldcodes_warmtepompen" ON "public"."meldcodes_warmtepompen" FOR SELECT TO "anon" USING (true);



CREATE POLICY "anon_read_meldcodes_zonneboilers" ON "public"."meldcodes_zonneboilers" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."company_profile" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."energiebelasting_aanvragen" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hoog_rendements_glas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."insulationRequirements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isolatie" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meldcodes_glas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meldcodes_isolatie" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meldcodes_ventilatie" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meldcodes_warmtepompen" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meldcodes_zonneboilers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ownerDocuments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."owners" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."requestDocuments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."staff_allowlist" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subsidie_aanvragen" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."svoh_aanvragen" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."warmtepompen" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."zonneboilers" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

















































































































































































GRANT ALL ON FUNCTION "public"."assign_staff_role"() TO "anon";
GRANT ALL ON FUNCTION "public"."assign_staff_role"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."assign_staff_role"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_staff_allowed"("user_email" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."is_staff_allowed"("user_email" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_staff_allowed"("user_email" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."set_created_by"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_created_by"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_created_by"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_products_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_products_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_products_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";



























GRANT ALL ON TABLE "public"."addresses" TO "anon";
GRANT ALL ON TABLE "public"."addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."addresses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company_profile" TO "anon";
GRANT ALL ON TABLE "public"."company_profile" TO "authenticated";
GRANT ALL ON TABLE "public"."company_profile" TO "service_role";



GRANT ALL ON TABLE "public"."energiebelasting_aanvragen" TO "anon";
GRANT ALL ON TABLE "public"."energiebelasting_aanvragen" TO "authenticated";
GRANT ALL ON TABLE "public"."energiebelasting_aanvragen" TO "service_role";



GRANT ALL ON TABLE "public"."hoog_rendements_glas" TO "anon";
GRANT ALL ON TABLE "public"."hoog_rendements_glas" TO "authenticated";
GRANT ALL ON TABLE "public"."hoog_rendements_glas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."high_performance_glass_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."high_performance_glass_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."high_performance_glass_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."insulationRequirements" TO "anon";
GRANT ALL ON TABLE "public"."insulationRequirements" TO "authenticated";
GRANT ALL ON TABLE "public"."insulationRequirements" TO "service_role";



GRANT ALL ON SEQUENCE "public"."insulationRequirements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."insulationRequirements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."insulationRequirements_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isolatie" TO "anon";
GRANT ALL ON TABLE "public"."isolatie" TO "authenticated";
GRANT ALL ON TABLE "public"."isolatie" TO "service_role";



GRANT ALL ON SEQUENCE "public"."insulation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."insulation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."insulation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."meldcodes_glas" TO "anon";
GRANT ALL ON TABLE "public"."meldcodes_glas" TO "authenticated";
GRANT ALL ON TABLE "public"."meldcodes_glas" TO "service_role";



GRANT ALL ON TABLE "public"."meldcodes_isolatie" TO "anon";
GRANT ALL ON TABLE "public"."meldcodes_isolatie" TO "authenticated";
GRANT ALL ON TABLE "public"."meldcodes_isolatie" TO "service_role";



GRANT ALL ON TABLE "public"."meldcodes_ventilatie" TO "anon";
GRANT ALL ON TABLE "public"."meldcodes_ventilatie" TO "authenticated";
GRANT ALL ON TABLE "public"."meldcodes_ventilatie" TO "service_role";



GRANT ALL ON TABLE "public"."meldcodes_warmtepompen" TO "anon";
GRANT ALL ON TABLE "public"."meldcodes_warmtepompen" TO "authenticated";
GRANT ALL ON TABLE "public"."meldcodes_warmtepompen" TO "service_role";



GRANT ALL ON TABLE "public"."meldcodes_zonneboilers" TO "anon";
GRANT ALL ON TABLE "public"."meldcodes_zonneboilers" TO "authenticated";
GRANT ALL ON TABLE "public"."meldcodes_zonneboilers" TO "service_role";



GRANT ALL ON TABLE "public"."ownerDocuments" TO "anon";
GRANT ALL ON TABLE "public"."ownerDocuments" TO "authenticated";
GRANT ALL ON TABLE "public"."ownerDocuments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ownerDocuments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ownerDocuments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ownerDocuments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."owners" TO "anon";
GRANT ALL ON TABLE "public"."owners" TO "authenticated";
GRANT ALL ON TABLE "public"."owners" TO "service_role";



GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."owners_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."requestDocuments" TO "anon";
GRANT ALL ON TABLE "public"."requestDocuments" TO "authenticated";
GRANT ALL ON TABLE "public"."requestDocuments" TO "service_role";



GRANT ALL ON TABLE "public"."requests" TO "anon";
GRANT ALL ON TABLE "public"."requests" TO "authenticated";
GRANT ALL ON TABLE "public"."requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."staff_allowlist" TO "anon";
GRANT ALL ON TABLE "public"."staff_allowlist" TO "authenticated";
GRANT ALL ON TABLE "public"."staff_allowlist" TO "service_role";



GRANT ALL ON TABLE "public"."subsidie_aanvragen" TO "anon";
GRANT ALL ON TABLE "public"."subsidie_aanvragen" TO "authenticated";
GRANT ALL ON TABLE "public"."subsidie_aanvragen" TO "service_role";



GRANT ALL ON TABLE "public"."svoh_aanvragen" TO "anon";
GRANT ALL ON TABLE "public"."svoh_aanvragen" TO "authenticated";
GRANT ALL ON TABLE "public"."svoh_aanvragen" TO "service_role";



GRANT ALL ON TABLE "public"."user_roles" TO "anon";
GRANT ALL ON TABLE "public"."user_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roles" TO "service_role";



GRANT ALL ON TABLE "public"."warmtepompen" TO "anon";
GRANT ALL ON TABLE "public"."warmtepompen" TO "authenticated";
GRANT ALL ON TABLE "public"."warmtepompen" TO "service_role";



GRANT ALL ON TABLE "public"."zonneboilers" TO "anon";
GRANT ALL ON TABLE "public"."zonneboilers" TO "authenticated";
GRANT ALL ON TABLE "public"."zonneboilers" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























